onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - bufferutil
  - cpu-features
  - esbuild
  - lefthook
  - msgpackr-extract
  - protobufjs
  - ssh2
  - unrs-resolver
  - utf-8-validate
